// Generated by setver tool, do not edit
using System.Reflection;
[assembly: AssemblyCopyright("Copyright \u00A9 2016 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.1.50")]
[assembly: AssemblyFileVersion("0.1.50")]
