/*
Win3mu - Windows 3 Emulator
Copyright (C) 2017 Topten Software.

Win3mu is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Win3mu is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Win3mu.  If not, see <http://www.gnu.org/licenses/>.
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Win3muCore
{
    public static class MessageNames
    {
        static MessageNames()
        {
            _map = new Dictionary<uint, string>();
            foreach (var e in _entries)
            {
                string name;
                if (_map.TryGetValue(e.message, out name))
                {
                    name += "|" + e.name;
                }
                else
                {
                    name = e.name;
                }
                _map[e.message] = name;
            }
        }

        public static string NameOfMessage(uint message)
        {
            string msgName;
            if (_map.TryGetValue(message, out msgName))
            {
                return string.Format("{0} (0x{1:X4})", msgName, message);
            }
            else
            {
                return string.Format("Unknown message: 0x{0:X4}", message);
            }
        }

        public static IEnumerable<KeyValuePair<ushort, string>> All
        {
            get
            {
                foreach (var e in _entries)
                {
                    yield return new KeyValuePair<ushort, string>(e.message, e.name);
                }
            }
        } 

        static Dictionary<uint, string> _map;

        struct Entry
        {
            public Entry(ushort m, string n)
            {
                message = m;
                name = n;
            }
            public ushort message;
            public string name;
        };

        static Entry[] _entries = new Entry[] {
            new Entry( 0x0000        , "WM_NULL" ),
            new Entry( 0x0001        , "WM_CREATE" ),
            new Entry( 0x0002        , "WM_DESTROY" ),
            new Entry( 0x0003        , "WM_MOVE" ),
            new Entry( 0x0005        , "WM_SIZE" ),
            new Entry( 0x0006        , "WM_ACTIVATE" ),
            new Entry( 0x0007        , "WM_SETFOCUS" ),
            new Entry( 0x0008        , "WM_KILLFOCUS" ),
            new Entry( 0x000a        , "WM_ENABLE" ),
            new Entry( 0x000b        , "WM_SETREDRAW" ),
            new Entry( 0x000c        , "WM_SETTEXT" ),
            new Entry( 0x000d        , "WM_GETTEXT" ),
            new Entry( 0x000e        , "WM_GETTEXTLENGTH" ),
            new Entry( 0x000f        , "WM_PAINT" ),
            new Entry( 0x0010        , "WM_CLOSE" ),
            new Entry( 0x0011        , "WM_QUERYENDSESSION" ),
            new Entry( 0x0012        , "WM_QUIT" ),
            new Entry( 0x0013        , "WM_QUERYOPEN" ),
            new Entry( 0x0014        , "WM_ERASEBKGND" ),
            new Entry( 0x0015        , "WM_SYSCOLORCHANGE" ),
            new Entry( 0x0016        , "WM_ENDSESSION" ),
            new Entry( 0x0018        , "WM_SHOWWINDOW" ),
            new Entry( 0x0019        , "WM_CTLCOLOR" ),
            new Entry( 0x001a        , "WM_WININICHANGE" ),
            new Entry( 0x001b        , "WM_DEVMODECHANGE" ),
            new Entry( 0x001c        , "WM_ACTIVATEAPP" ),
            new Entry( 0x001d        , "WM_FONTCHANGE" ),
            new Entry( 0x001e        , "WM_TIMECHANGE" ),
            new Entry( 0x001f        , "WM_CANCELMODE" ),
            new Entry( 0x0020        , "WM_SETCURSOR" ),
            new Entry( 0x0021        , "WM_MOUSEACTIVATE" ),
            new Entry( 0x0022        , "WM_CHILDACTIVATE" ),
            new Entry( 0x0023        , "WM_QUEUESYNC" ),
            new Entry( 0x0024        , "WM_GETMINMAXINFO" ),
            new Entry( 0x0026        , "WM_PAINTICON" ),
            new Entry( 0x0027        , "WM_ICONERASEBKGND" ),
            new Entry( 0x0028        , "WM_NEXTDLGCTL" ),
            new Entry( 0x002a        , "WM_SPOOLERSTATUS" ),
            new Entry( 0x002b        , "WM_DRAWITEM" ),
            new Entry( 0x002c        , "WM_MEASUREITEM" ),
            new Entry( 0x002d        , "WM_DELETEITEM" ),
            new Entry( 0x002e        , "WM_VKEYTOITEM" ),
            new Entry( 0x002f        , "WM_CHARTOITEM" ),
            new Entry( 0x0030        , "WM_SETFONT" ),
            new Entry( 0x0031        , "WM_GETFONT" ),
            new Entry( 0x0032        , "WM_SETHOTKEY" ),
            new Entry( 0x0033        , "WM_GETHOTKEY" ),
            new Entry( 0x0037        , "WM_QUERYDRAGICON" ),
            new Entry( 0x0039        , "WM_COMPAREITEM" ),
            new Entry( 0x003d        , "WM_GETOBJECT" ),
            new Entry( 0x0041        , "WM_COMPACTING" ),
            new Entry( 0x0044        , "WM_COMMNOTIFY" ),
            new Entry( 0x0046        , "WM_WINDOWPOSCHANGING" ),
            new Entry( 0x0047        , "WM_WINDOWPOSCHANGED" ),
            new Entry( 0x0048        , "WM_POWER" ),
            new Entry( 0x0049        , "WM_COPYGLOBALDATA" ),
            new Entry( 0x004a        , "WM_COPYDATA" ),
            new Entry( 0x004b        , "WM_CANCELJOURNAL" ),
            new Entry( 0x004e        , "WM_NOTIFY" ),
            new Entry( 0x0050        , "WM_INPUTLANGCHANGEREQUEST" ),
            new Entry( 0x0051        , "WM_INPUTLANGCHANGE" ),
            new Entry( 0x0052        , "WM_TCARD" ),
            new Entry( 0x0053        , "WM_HELP" ),
            new Entry( 0x0054        , "WM_USERCHANGED" ),
            new Entry( 0x0055        , "WM_NOTIFYFORMAT" ),
            new Entry( 0x007b        , "WM_CONTEXTMENU" ),
            new Entry( 0x007c        , "WM_STYLECHANGING" ),
            new Entry( 0x007d        , "WM_STYLECHANGED" ),
            new Entry( 0x007e        , "WM_DISPLAYCHANGE" ),
            new Entry( 0x007f        , "WM_GETICON" ),
            new Entry( 0x0080        , "WM_SETICON" ),
            new Entry( 0x0081        , "WM_NCCREATE" ),
            new Entry( 0x0082        , "WM_NCDESTROY" ),
            new Entry( 0x0083        , "WM_NCCALCSIZE" ),
            new Entry( 0x0084        , "WM_NCHITTEST" ),
            new Entry( 0x0085        , "WM_NCPAINT" ),
            new Entry( 0x0086        , "WM_NCACTIVATE" ),
            new Entry( 0x0087        , "WM_GETDLGCODE" ),
            new Entry( 0x0088        , "WM_SYNCPAINT" ),
            new Entry( 0x00a0        , "WM_NCMOUSEMOVE" ),
            new Entry( 0x00a1        , "WM_NCLBUTTONDOWN" ),
            new Entry( 0x00a2        , "WM_NCLBUTTONUP" ),
            new Entry( 0x00a3        , "WM_NCLBUTTONDBLCLK" ),
            new Entry( 0x00a4        , "WM_NCRBUTTONDOWN" ),
            new Entry( 0x00a5        , "WM_NCRBUTTONUP" ),
            new Entry( 0x00a6        , "WM_NCRBUTTONDBLCLK" ),
            new Entry( 0x00a7        , "WM_NCMBUTTONDOWN" ),
            new Entry( 0x00a8        , "WM_NCMBUTTONUP" ),
            new Entry( 0x00a9        , "WM_NCMBUTTONDBLCLK" ),
            new Entry( 0x00ab        , "WM_NCXBUTTONDOWN" ),
            new Entry( 0x00ac        , "WM_NCXBUTTONUP" ),
            new Entry( 0x00ad        , "WM_NCXBUTTONDBLCLK" ),
            new Entry( 0x00e0        , "SBM_SETPOS" ),
            new Entry( 0x00e1        , "SBM_GETPOS" ),
            new Entry( 0x00e2        , "SBM_SETRANGE" ),
            new Entry( 0x00e3        , "SBM_GETRANGE" ),
            new Entry( 0x00e4        , "SBM_ENABLE_ARROWS" ),
            new Entry( 0x00e6        , "SBM_SETRANGEREDRAW" ),
            new Entry( 0x00e9        , "SBM_SETSCROLLINFO" ),
            new Entry( 0x00ea        , "SBM_GETSCROLLINFO" ),
            new Entry( 0x00eb        , "SBM_GETSCROLLBARINFO" ),
            new Entry( 0x00ff        , "WM_INPUT" ),
            new Entry( 0x0100        , "WM_KEYDOWN" ),
            new Entry( 0x0100        , "WM_KEYFIRST" ),
            new Entry( 0x0101        , "WM_KEYUP" ),
            new Entry( 0x0102        , "WM_CHAR" ),
            new Entry( 0x0103        , "WM_DEADCHAR" ),
            new Entry( 0x0104        , "WM_SYSKEYDOWN" ),
            new Entry( 0x0105        , "WM_SYSKEYUP" ),
            new Entry( 0x0106        , "WM_SYSCHAR" ),
            new Entry( 0x0107        , "WM_SYSDEADCHAR" ),
            new Entry( 0x0108        , "WM_KEYLAST" ),
            new Entry( 0x0109        , "WM_UNICHAR" ),
            new Entry( 0x0109        , "WM_WNT_CONVERTREQUESTEX" ),
            new Entry( 0x010a        , "WM_CONVERTREQUEST" ),
            new Entry( 0x010b        , "WM_CONVERTRESULT" ),
            new Entry( 0x010c        , "WM_INTERIM" ),
            new Entry( 0x010d        , "WM_IME_STARTCOMPOSITION" ),
            new Entry( 0x010e        , "WM_IME_ENDCOMPOSITION" ),
            new Entry( 0x010f        , "WM_IME_COMPOSITION" ),
            new Entry( 0x010f        , "WM_IME_KEYLAST" ),
            new Entry( 0x0110        , "WM_INITDIALOG" ),
            new Entry( 0x0111        , "WM_COMMAND" ),
            new Entry( 0x0112        , "WM_SYSCOMMAND" ),
            new Entry( 0x0113        , "WM_TIMER" ),
            new Entry( 0x0114        , "WM_HSCROLL" ),
            new Entry( 0x0115        , "WM_VSCROLL" ),
            new Entry( 0x0116        , "WM_INITMENU" ),
            new Entry( 0x0117        , "WM_INITMENUPOPUP" ),
            new Entry( 0x0118        , "WM_SYSTIMER" ),
            new Entry( 0x011f        , "WM_MENUSELECT" ),
            new Entry( 0x0120        , "WM_MENUCHAR" ),
            new Entry( 0x0121        , "WM_ENTERIDLE" ),
            new Entry( 0x0122        , "WM_MENURBUTTONUP" ),
            new Entry( 0x0123        , "WM_MENUDRAG" ),
            new Entry( 0x0124        , "WM_MENUGETOBJECT" ),
            new Entry( 0x0125        , "WM_UNINITMENUPOPUP" ),
            new Entry( 0x0126        , "WM_MENUCOMMAND" ),
            new Entry( 0x0127        , "WM_CHANGEUISTATE" ),
            new Entry( 0x0128        , "WM_UPDATEUISTATE" ),
            new Entry( 0x0129        , "WM_QUERYUISTATE" ),
            new Entry( 0x0132        , "WM_CTLCOLORMSGBOX" ),
            new Entry( 0x0133        , "WM_CTLCOLOREDIT" ),
            new Entry( 0x0134        , "WM_CTLCOLORLISTBOX" ),
            new Entry( 0x0135        , "WM_CTLCOLORBTN" ),
            new Entry( 0x0136        , "WM_CTLCOLORDLG" ),
            new Entry( 0x0137        , "WM_CTLCOLORSCROLLBAR" ),
            new Entry( 0x0138        , "WM_CTLCOLORSTATIC" ),
            new Entry( 0x0200        , "WM_MOUSEFIRST" ),
            new Entry( 0x0200        , "WM_MOUSEMOVE" ),
            new Entry( 0x0201        , "WM_LBUTTONDOWN" ),
            new Entry( 0x0202        , "WM_LBUTTONUP" ),
            new Entry( 0x0203        , "WM_LBUTTONDBLCLK" ),
            new Entry( 0x0204        , "WM_RBUTTONDOWN" ),
            new Entry( 0x0205        , "WM_RBUTTONUP" ),
            new Entry( 0x0206        , "WM_RBUTTONDBLCLK" ),
            new Entry( 0x0207        , "WM_MBUTTONDOWN" ),
            new Entry( 0x0208        , "WM_MBUTTONUP" ),
            new Entry( 0x0209        , "WM_MBUTTONDBLCLK" ),
            new Entry( 0x0209        , "WM_MOUSELAST" ),
            new Entry( 0x020a        , "WM_MOUSEWHEEL" ),
            new Entry( 0x020b        , "WM_XBUTTONDOWN" ),
            new Entry( 0x020c        , "WM_XBUTTONUP" ),
            new Entry( 0x020d        , "WM_XBUTTONDBLCLK" ),
            new Entry( 0x0210        , "WM_PARENTNOTIFY" ),
            new Entry( 0x0211        , "WM_ENTERMENULOOP" ),
            new Entry( 0x0212        , "WM_EXITMENULOOP" ),
            new Entry( 0x0213        , "WM_NEXTMENU" ),
            new Entry( 0x0214        , "WM_SIZING" ),
            new Entry( 0x0215        , "WM_CAPTURECHANGED" ),
            new Entry( 0x0216        , "WM_MOVING" ),
            new Entry( 0x0218        , "WM_POWERBROADCAST" ),
            new Entry( 0x0219        , "WM_DEVICECHANGE" ),
            new Entry( 0x0220        , "WM_MDICREATE" ),
            new Entry( 0x0221        , "WM_MDIDESTROY" ),
            new Entry( 0x0222        , "WM_MDIACTIVATE" ),
            new Entry( 0x0223        , "WM_MDIRESTORE" ),
            new Entry( 0x0224        , "WM_MDINEXT" ),
            new Entry( 0x0225        , "WM_MDIMAXIMIZE" ),
            new Entry( 0x0226        , "WM_MDITILE" ),
            new Entry( 0x0227        , "WM_MDICASCADE" ),
            new Entry( 0x0228        , "WM_MDIICONARRANGE" ),
            new Entry( 0x0229        , "WM_MDIGETACTIVE" ),
            new Entry( 0x0230        , "WM_MDISETMENU" ),
            new Entry( 0x0231        , "WM_ENTERSIZEMOVE" ),
            new Entry( 0x0232        , "WM_EXITSIZEMOVE" ),
            new Entry( 0x0233        , "WM_DROPFILES" ),
            new Entry( 0x0234        , "WM_MDIREFRESHMENU" ),
            new Entry( 0x0280        , "WM_IME_REPORT" ),
            new Entry( 0x0281        , "WM_IME_SETCONTEXT" ),
            new Entry( 0x0282        , "WM_IME_NOTIFY" ),
            new Entry( 0x0283        , "WM_IME_CONTROL" ),
            new Entry( 0x0284        , "WM_IME_COMPOSITIONFULL" ),
            new Entry( 0x0285        , "WM_IME_SELECT" ),
            new Entry( 0x0286        , "WM_IME_CHAR" ),
            new Entry( 0x0288        , "WM_IME_REQUEST" ),
            new Entry( 0x0290        , "WM_IMEKEYDOWN" ),
            new Entry( 0x0290        , "WM_IME_KEYDOWN" ),
            new Entry( 0x0291        , "WM_IMEKEYUP" ),
            new Entry( 0x0291        , "WM_IME_KEYUP" ),
            new Entry( 0x02a0        , "WM_NCMOUSEHOVER" ),
            new Entry( 0x02a1        , "WM_MOUSEHOVER" ),
            new Entry( 0x02a2        , "WM_NCMOUSELEAVE" ),
            new Entry( 0x02a3        , "WM_MOUSELEAVE" ),
            new Entry( 0x0300        , "WM_CUT" ),
            new Entry( 0x0301        , "WM_COPY" ),
            new Entry( 0x0302        , "WM_PASTE" ),
            new Entry( 0x0303        , "WM_CLEAR" ),
            new Entry( 0x0304        , "WM_UNDO" ),
            new Entry( 0x0305        , "WM_RENDERFORMAT" ),
            new Entry( 0x0306        , "WM_RENDERALLFORMATS" ),
            new Entry( 0x0307        , "WM_DESTROYCLIPBOARD" ),
            new Entry( 0x0308        , "WM_DRAWCLIPBOARD" ),
            new Entry( 0x0309        , "WM_PAINTCLIPBOARD" ),
            new Entry( 0x030a        , "WM_VSCROLLCLIPBOARD" ),
            new Entry( 0x030b        , "WM_SIZECLIPBOARD" ),
            new Entry( 0x030c        , "WM_ASKCBFORMATNAME" ),
            new Entry( 0x030d        , "WM_CHANGECBCHAIN" ),
            new Entry( 0x030e        , "WM_HSCROLLCLIPBOARD" ),
            new Entry( 0x030f        , "WM_QUERYNEWPALETTE" ),
            new Entry( 0x0310        , "WM_PALETTEISCHANGING" ),
            new Entry( 0x0311        , "WM_PALETTECHANGED" ),
            new Entry( 0x0312        , "WM_HOTKEY" ),
            new Entry( 0x0317        , "WM_PRINT" ),
            new Entry( 0x0318        , "WM_PRINTCLIENT" ),
            new Entry( 0x0319        , "WM_APPCOMMAND" ),
            new Entry( 0x0358        , "WM_HANDHELDFIRST" ),
            new Entry( 0x035f        , "WM_HANDHELDLAST" ),
            new Entry( 0x0360        , "WM_AFXFIRST" ),
            new Entry( 0x037f        , "WM_AFXLAST" ),
            new Entry( 0x0380        , "WM_PENWINFIRST" ),
            new Entry( 0x0381        , "WM_RCRESULT" ),
            new Entry( 0x0382        , "WM_HOOKRCRESULT" ),
            new Entry( 0x0383        , "WM_GLOBALRCCHANGE" ),
            new Entry( 0x0383        , "WM_PENMISCINFO" ),
            new Entry( 0x0384        , "WM_SKB" ),
            new Entry( 0x0385        , "WM_HEDITCTL" ),
            new Entry( 0x0385        , "WM_PENCTL" ),
            new Entry( 0x0386        , "WM_PENMISC" ),
            new Entry( 0x0387        , "WM_CTLINIT" ),
            new Entry( 0x0388        , "WM_PENEVENT" ),
            new Entry( 0x038f        , "WM_PENWINLAST" ),

            new Entry(WinCommon.WM_USER+0, "BM_GETCHECK(16)"),
            new Entry(WinCommon.WM_USER+1, "BM_SETCHECK(16)"),
            new Entry(WinCommon.WM_USER+2, "BM_GETSTATE(16)"),
            new Entry(WinCommon.WM_USER+3, "BM_SETSTATE(16)"),
            new Entry(WinCommon.WM_USER+4, "BM_SETSTYLE(16)"),
            new Entry(WinCommon.WM_USER+0, "STM_SETICON(16)"),
            new Entry(WinCommon.WM_USER+1, "STM_GETICON(16)"),
            new Entry(WinCommon.WM_USER+0, "EM_GETSEL(16)"),
            new Entry(WinCommon.WM_USER+1, "EM_SETSEL(16)"),
            new Entry(WinCommon.WM_USER+2, "EM_GETRECT(16)"),
            new Entry(WinCommon.WM_USER+3, "EM_SETRECT(16)"),
            new Entry(WinCommon.WM_USER+4, "EM_SETRECTNP(16)"),
            new Entry(WinCommon.WM_USER+6, "EM_LINESCROLL(16)"),
            new Entry(WinCommon.WM_USER+8, "EM_GETMODIFY(16)"),
            new Entry(WinCommon.WM_USER+9, "EM_SETMODIFY(16)"),
            new Entry(WinCommon.WM_USER+10, "EM_GETLINECOUNT(16)"),
            new Entry(WinCommon.WM_USER+11, "EM_LINEINDEX(16)"),
            new Entry(WinCommon.WM_USER+12, "EM_SETHANDLE(16)"),
            new Entry(WinCommon.WM_USER+13, "EM_GETHANDLE(16)"),
            new Entry(WinCommon.WM_USER+17, "EM_LINELENGTH(16)"),
            new Entry(WinCommon.WM_USER+18, "EM_REPLACESEL(16)"),
            new Entry(WinCommon.WM_USER+19, "EM_SETFONT(16)"),
            new Entry(WinCommon.WM_USER+20, "EM_GETLINE(16)"),
            new Entry(WinCommon.WM_USER+21, "EM_LIMITTEXT(16)"),
            new Entry(WinCommon.WM_USER+22, "EM_CANUNDO(16)"),
            new Entry(WinCommon.WM_USER+23, "EM_UNDO (16)"),
            new Entry(WinCommon.WM_USER+24, "EM_FMTLINES(16)"),
            new Entry(WinCommon.WM_USER+25, "EM_LINEFROMCHAR(16)"),
            new Entry(WinCommon.WM_USER+26, "EM_SETWORDBREAK(16)"),
            new Entry(WinCommon.WM_USER+27, "EM_SETTABSTOPS(16)"),
            new Entry(WinCommon.WM_USER+28, "EM_SETPASSWORDCHAR(16)"),
            new Entry(WinCommon.WM_USER+29, "EM_EMPTYUNDOBUFFER(16)"),
            new Entry(WinCommon.WM_USER+30, "EM_GETFIRSTVISIBLELINE(16)"),
            new Entry(WinCommon.WM_USER+31, "EM_SETREADONLY(16)"),
            new Entry(WinCommon.WM_USER+32, "EM_SETWORDBREAKPROC(16)"),
            new Entry(WinCommon.WM_USER+33, "EM_GETWORDBREAKPROC(16)"),
            new Entry(WinCommon.WM_USER+34, "EM_GETPASSWORDCHAR(16)"),
            new Entry(WinCommon.WM_USER+1, "LB_ADDSTRING(16)"),
            new Entry(WinCommon.WM_USER+2, "LB_INSERTSTRING(16)"),
            new Entry(WinCommon.WM_USER+3, "LB_DELETESTRING(16)"),
            new Entry(WinCommon.WM_USER+5, "LB_RESETCONTENT(16)"),
            new Entry(WinCommon.WM_USER+6, "LB_SETSEL(16)"),
            new Entry(WinCommon.WM_USER+7, "LB_SETCURSEL(16)"),
            new Entry(WinCommon.WM_USER+8, "LB_GETSEL(16)"),
            new Entry(WinCommon.WM_USER+9, "LB_GETCURSEL(16)"),
            new Entry(WinCommon.WM_USER+10, "LB_GETTEXT(16)"),
            new Entry(WinCommon.WM_USER+11, "LB_GETTEXTLEN(16)"),
            new Entry(WinCommon.WM_USER+12, "LB_GETCOUNT(16)"),
            new Entry(WinCommon.WM_USER+13, "LB_SELECTSTRING(16)"),
            new Entry(WinCommon.WM_USER+14, "LB_DIR	(16)"),
            new Entry(WinCommon.WM_USER+15, "LB_GETTOPINDEX(16)"),
            new Entry(WinCommon.WM_USER+16, "LB_FINDSTRING(16)"),
            new Entry(WinCommon.WM_USER+17, "LB_GETSELCOUNT(16)"),
            new Entry(WinCommon.WM_USER+18, "LB_GETSELITEMS(16)"),
            new Entry(WinCommon.WM_USER+19, "LB_SETTABSTOPS(16)"),
            new Entry(WinCommon.WM_USER+20, "LB_GETHORIZONTALEXTENT(16)"),
            new Entry(WinCommon.WM_USER+21, "LB_SETHORIZONTALEXTENT(16)"),
            new Entry(WinCommon.WM_USER+22, "LB_SETCOLUMNWIDTH(16)"),
            new Entry(WinCommon.WM_USER+24, "LB_SETTOPINDEX(16)"),
            new Entry(WinCommon.WM_USER+25, "LB_GETITEMRECT(16)"),
            new Entry(WinCommon.WM_USER+26, "LB_GETITEMDATA(16)"),
            new Entry(WinCommon.WM_USER+27, "LB_SETITEMDATA(16)"),
            new Entry(WinCommon.WM_USER+28, "LB_SELITEMRANGE(16)"),
            new Entry(WinCommon.WM_USER+31, "LB_SETCARETINDEX(16)"),
            new Entry(WinCommon.WM_USER+32, "LB_GETCARETINDEX(16)"),
            new Entry(WinCommon.WM_USER+33, "LB_SETITEMHEIGHT(16)"),
            new Entry(WinCommon.WM_USER+34, "LB_GETITEMHEIGHT(16)"),
            new Entry(WinCommon.WM_USER+35, "LB_FINDSTRINGEXACT(16)"),
            new Entry(WinCommon.WM_USER+0, "CB_GETEDITSEL(16)"),
            new Entry(WinCommon.WM_USER+1, "CB_LIMITTEXT(16)"),
            new Entry(WinCommon.WM_USER+2, "CB_SETEDITSEL(16)"),
            new Entry(WinCommon.WM_USER+3, "CB_ADDSTRING(16)"),
            new Entry(WinCommon.WM_USER+4, "CB_DELETESTRING(16)"),
            new Entry(WinCommon.WM_USER+5, "CB_DIR(16)"),
            new Entry(WinCommon.WM_USER+6, "CB_GETCOUNT(16)"),
            new Entry(WinCommon.WM_USER+7, "CB_GETCURSEL(16)"),
            new Entry(WinCommon.WM_USER+8, "CB_GETLBTEXT(16)"),
            new Entry(WinCommon.WM_USER+9, "CB_GETLBTEXTLEN(16)"),
            new Entry(WinCommon.WM_USER+10, "CB_INSERTSTRING(16)"),
            new Entry(WinCommon.WM_USER+11, "CB_RESETCONTENT(16)"),
            new Entry(WinCommon.WM_USER+12, "CB_FINDSTRING(16)"),
            new Entry(WinCommon.WM_USER+13, "CB_SELECTSTRING(16)"),
            new Entry(WinCommon.WM_USER+14, "CB_SETCURSEL(16)"),
            new Entry(WinCommon.WM_USER+15, "CB_SHOWDROPDOWN(16)"),
            new Entry(WinCommon.WM_USER+16, "CB_GETITEMDATA(16)"),
            new Entry(WinCommon.WM_USER+17, "CB_SETITEMDATA(16)"),
            new Entry(WinCommon.WM_USER+18, "CB_GETDROPPEDCONTROLRECT(16)"),
            new Entry(WinCommon.WM_USER+19, "CB_SETITEMHEIGHT(16)"),
            new Entry(WinCommon.WM_USER+20, "CB_GETITEMHEIGHT(16)"),
            new Entry(WinCommon.WM_USER+21, "CB_SETEXTENDEDUI(16)"),
            new Entry(WinCommon.WM_USER+22, "CB_GETEXTENDEDUI(16)"),
            new Entry(WinCommon.WM_USER+23, "CB_GETDROPPEDSTATE(16)"),
            new Entry(WinCommon.WM_USER+24, "CB_FINDSTRINGEXACT(16)"),

            new Entry(0x00F0, "BM_GETCHECK"),
            new Entry(0x00F1, "BM_SETCHECK"),
            new Entry(0x00F2, "BM_GETSTATE"),
            new Entry(0x00F3, "BM_SETSTATE"),
            new Entry(0x00F4, "BM_SETSTYLE"),
            new Entry(0x00F5, "BM_CLICK"),
            new Entry(0x00F6, "BM_GETIMAGE"),
            new Entry(0x00F7, "BM_SETIMAGE"),

            new Entry(0x0170, "STM_SETICON(32)"),
            new Entry(0x0171, "STM_GETICON(32)"),
            new Entry(0x0172, "STM_SETIMAGE(32)"),
            new Entry(0x0173, "STM_GETIMAGE(32)"),
            new Entry(0x0180, "LB_ADDSTRING(32)"),
            new Entry(0x0181, "LB_INSERTSTRING(32)"),
            new Entry(0x0182, "LB_DELETESTRING(32)"),
            new Entry(0x0183, "LB_SELITEMRANGEEX(32)"),
            new Entry(0x0184, "LB_RESETCONTENT(32)"),
            new Entry(0x0185, "LB_SETSEL(32)"),
            new Entry(0x0186, "LB_SETCURSEL(32)"),
            new Entry(0x0187, "LB_GETSEL(32)"),
            new Entry(0x0188, "LB_GETCURSEL(32)"),
            new Entry(0x0189, "LB_GETTEXT(32)"),
            new Entry(0x018A, "LB_GETTEXTLEN(32)"),
            new Entry(0x018B, "LB_GETCOUNT(32)"),
            new Entry(0x018C, "LB_SELECTSTRING(32)"),
            new Entry(0x018D, "LB_DIR(32)"),
            new Entry(0x018E, "LB_GETTOPINDEX(32)"),
            new Entry(0x018F, "LB_FINDSTRING(32)"),
            new Entry(0x0190, "LB_GETSELCOUNT(32)"),
            new Entry(0x0191, "LB_GETSELITEMS(32)"),
            new Entry(0x0192, "LB_SETTABSTOPS(32)"),
            new Entry(0x0193, "LB_GETHORIZONTALEXTENT(32)"),
            new Entry(0x0194, "LB_SETHORIZONTALEXTENT(32)"),
            new Entry(0x0195, "LB_SETCOLUMNWIDTH(32)"),
            new Entry(0x0196, "LB_ADDFILE(32)"),
            new Entry(0x0197, "LB_SETTOPINDEX(32)"),
            new Entry(0x0198, "LB_GETITEMRECT(32)"),
            new Entry(0x0199, "LB_GETITEMDATA(32)"),
            new Entry(0x019A, "LB_SETITEMDATA(32)"),
            new Entry(0x019B, "LB_SELITEMRANGE(32)"),
            new Entry(0x019C, "LB_SETANCHORINDEX(32)"),
            new Entry(0x019D, "LB_GETANCHORINDEX(32)"),
            new Entry(0x019E, "LB_SETCARETINDEX(32)"),
            new Entry(0x019F, "LB_GETCARETINDEX(32)"),
            new Entry(0x01A0, "LB_SETITEMHEIGHT(32)"),
            new Entry(0x01A1, "LB_GETITEMHEIGHT(32)"),
            new Entry(0x01A2, "LB_FINDSTRINGEXACT(32)"),
            new Entry(0x01A5, "LB_SETLOCALE(32)"),
            new Entry(0x01A6, "LB_GETLOCALE(32)"),
            new Entry(0x01A7, "LB_SETCOUNT(32)"),
            new Entry(0x01A8, "LB_INITSTORAGE(32)"),
            new Entry(0x01A9, "LB_ITEMFROMPOINT(32)"),
            new Entry(0x01B1, "LB_MULTIPLEADDSTRING(32)"),
            new Entry(0x01B2, "LB_GETLISTBOXINFO(32)"),
            new Entry(0x0140, "CB_GETEDITSEL(32)"),
            new Entry(0x0141, "CB_LIMITTEXT(32)"),
            new Entry(0x0142, "CB_SETEDITSEL(32)"),
            new Entry(0x0143, "CB_ADDSTRING(32)"),
            new Entry(0x0144, "CB_DELETESTRING(32)"),
            new Entry(0x0145, "CB_DIR(32)"),
            new Entry(0x0146, "CB_GETCOUNT(32)"),
            new Entry(0x0147, "CB_GETCURSEL(32)"),
            new Entry(0x0148, "CB_GETLBTEXT(32)"),
            new Entry(0x0149, "CB_GETLBTEXTLEN(32)"),
            new Entry(0x014A, "CB_INSERTSTRING(32)"),
            new Entry(0x014B, "CB_RESETCONTENT(32)"),
            new Entry(0x014C, "CB_FINDSTRING(32)"),
            new Entry(0x014D, "CB_SELECTSTRING(32)"),
            new Entry(0x014E, "CB_SETCURSEL(32)"),
            new Entry(0x014F, "CB_SHOWDROPDOWN(32)"),
            new Entry(0x0150, "CB_GETITEMDATA(32)"),
            new Entry(0x0151, "CB_SETITEMDATA(32)"),
            new Entry(0x0152, "CB_GETDROPPEDCONTROLRECT(32)"),
            new Entry(0x0153, "CB_SETITEMHEIGHT(32)"),
            new Entry(0x0154, "CB_GETITEMHEIGHT(32)"),
            new Entry(0x0155, "CB_SETEXTENDEDUI(32)"),
            new Entry(0x0156, "CB_GETEXTENDEDUI(32)"),
            new Entry(0x0157, "CB_GETDROPPEDSTATE(32)"),
            new Entry(0x0158, "CB_FINDSTRINGEXACT(32)"),
            new Entry(0x0159, "CB_SETLOCALE(32)"),
            new Entry(0x015A, "CB_GETLOCALE(32)"),
            new Entry(0x015b, "CB_GETTOPINDEX(32)"),
            new Entry(0x015c, "CB_SETTOPINDEX(32)"),
            new Entry(0x015d, "CB_GETHORIZONTALEXTENT(32)"),
            new Entry(0x015e, "CB_SETHORIZONTALEXTENT(32)"),
            new Entry(0x015f, "CB_GETDROPPEDWIDTH(32)"),
            new Entry(0x0160, "CB_SETDROPPEDWIDTH(32)"),
            new Entry(0x0161, "CB_INITSTORAGE(32)"),
            new Entry(0x0163, "CB_MULTIPLEADDSTRING(32)"),
            new Entry(0x0164, "CB_GETCOMBOBOXINFO(32)"),
            new Entry(0x00B0, "EM_GETSEL(32)"),
            new Entry(0x00B1, "EM_SETSEL(32)"),
            new Entry(0x00B2, "EM_GETRECT(32)"),
            new Entry(0x00B3, "EM_SETRECT(32)"),
            new Entry(0x00B4, "EM_SETRECTNP(32)"),
            new Entry(0x00B5, "EM_SCROLL(32)"),
            new Entry(0x00B6, "EM_LINESCROLL(32)"),
            new Entry(0x00B7, "EM_SCROLLCARET(32)"),
            new Entry(0x00B8, "EM_GETMODIFY(32)"),
            new Entry(0x00B9, "EM_SETMODIFY(32)"),
            new Entry(0x00BA, "EM_GETLINECOUNT(32)"),
            new Entry(0x00BB, "EM_LINEINDEX(32)"),
            new Entry(0x00BC, "EM_SETHANDLE(32)"),
            new Entry(0x00BD, "EM_GETHANDLE(32)"),
            new Entry(0x00BE, "EM_GETTHUMB(32)"),
            new Entry(0x00C1, "EM_LINELENGTH(32)"),
            new Entry(0x00C2, "EM_REPLACESEL(32)"),
            new Entry(0x00C4, "EM_GETLINE(32)"),
            new Entry(0x00C5, "EM_SETLIMITTEXT(32)"),
            new Entry(0x00C6, "EM_CANUNDO(32)"),
            new Entry(0x00C7, "EM_UNDO(32)"),
            new Entry(0x00C8, "EM_FMTLINES(32)"),
            new Entry(0x00C9, "EM_LINEFROMCHAR(32)"),
            new Entry(0x00CB, "EM_SETTABSTOPS(32)"),
            new Entry(0x00CC, "EM_SETPASSWORDCHAR(32)"),
            new Entry(0x00CD, "EM_EMPTYUNDOBUFFER(32)"),
            new Entry(0x00CE, "EM_GETFIRSTVISIBLELINE(32)"),
            new Entry(0x00CF, "EM_SETREADONLY(32)"),
            new Entry(0x00D0, "EM_SETWORDBREAKPROC(32)"),
            new Entry(0x00D1, "EM_GETWORDBREAKPROC(32)"),
            new Entry(0x00D2, "EM_GETPASSWORDCHAR(32)"),
            new Entry(0x00D3, "EM_SETMARGINS(32)"),
            new Entry(0x00D4, "EM_GETMARGINS(32)"),
            new Entry(0x00D5, "EM_GETLIMITTEXT(32)"),
            new Entry(0x00D6, "EM_POSFROMCHAR(32)"),
            new Entry(0x00D7, "EM_CHARFROMPOS(32)"),
            new Entry(0x00D8, "EM_SETIMESTATUS(32)"),
            new Entry(0x00D9, "EM_GETIMESTATUS(32)"),

        };
    }
}
